### ISSUE TITLE
N卡问题还有没有更好的解决方法？

### ISSUE THREAD

**Issue by Alexander-Huang** [Bit0r/CSAPP#1]
如题。我之前试过多次装N卡驱动，包括使用manjaro自带mhwd与官网下载.run文件，结果基本都是无法进入桌面（gnome），或者进入桌面后动画效果无法开启（dde）。  
1.上网搜索发现gnome与nvidia的OpenGL不兼容，并且提到有可以使两者兼容的安装方法？  
2.通过mhwd安装nvidia后，nvidia xsettings打开显示配置文件中没有......酷安老哥@领主巴尔扎克用的Linux内核版本跟我不同，N卡型号也不同，却遇到了同样的问题，可能mhwd根本就没有装好驱动？？？  
反正我现在nouveau勉强度日，也没出什么大问题>_<

**Comment by Bit0r** [comment]
暂时没有，Linux基本都没法用这个东西
